# Generated by Django 3.2.9 on 2022-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='beden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_isim', models.CharField(max_length=10)),
            ],
        ),
    ]
