# Generated by Django 3.2.9 on 2022-04-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0002_beden'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_isimi', models.CharField(max_length=100)),
                ('urun_stog', models.IntegerField()),
                ('urun_fiyat', models.IntegerField()),
                ('urun_beden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kategori.beden')),
                ('urun_kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategori.kategoriler')),
            ],
        ),
    ]
