# Generated by Django 3.2.9 on 2022-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0003_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_resim',
            field=models.FileField(blank=True, null=True, upload_to='urunresim/', verbose_name='Ürün Resim'),
        ),
    ]
