# Generated by Django 3.2.9 on 2022-04-26 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0004_urunler_urun_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_aciklama',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
