# Generated by Django 3.2.9 on 2022-04-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0006_resimler'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kategori.urunler')),
                ('user_bilgisi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
